### PR TITLE
Fix Toasty and Cameron not leaving the scene

### LINKED ISSUE #93: Toasty never leaves the developer room
https://github.com/pixequil/oso-game-1/assets/49569238/e483a053-8117-4fe0-ae2b-8a5b699151bd

### PR DESCRIPTION
**Pull request by Martysh12**
Toasty now finally leaves the developer room

https://github.com/pixequil/oso-game-1/assets/49569238/770d47e6-1032-4714-82c6-980bf9f0cb10

Fixes #93

### CODE REVIEW

**Comment by Martysh12** [comment]
oh I thought the scene leaking thing was a feature

**Comment by funnyboy044** [comment]
can we fix the scene leaking in another issue?

**Comment by pixequil** [comment]
we could, i just thought it was the same issue as this since they were basically caused by the same underlying assumption (that a scene ends when another block starts)

**Review by funnyboy044 — APPROVED** [review]
Toasty works, scene leaking can fixed in another issue

**Comment by Martysh12** [comment]
> scene leaking can fixed in another issue

It looks like scene leaking is already fixed, isn't it?

**Pull request merged**
