### PR TITLE
Animate BT Net's swaying

### LINKED ISSUE #97: animate BT Net swaying when he speaks
after seeing Security Cameron's single sprite animate when talking, i started to think the same could be done for the other characters with no mouth animation. in this case, BT Net could sway left and right (with the axis on his handle) kind of like how a butterfly net moves.

this isn't that important.

### PR DESCRIPTION
**Pull request by Martysh12**
https://github.com/pixequil/oso-game-1/assets/49569238/3706c238-1e56-49b5-ad09-eaa0cccca765

Fixes #97

### CODE REVIEW

**Comment by pixequil** [comment]
seems a bit too gentle? what do other people think?

**Comment by Martysh12** [comment]
> seems a bit too gentle

well, yes, it's swaying. It shouldn't be too extreme because it will be too weird.

**Comment by pixequil** [comment]
that makes sense. i mostly brought this up because I thought of it as an equivalent to the violent bouncing that Security Cameron does when speaking. since it feels a little weird that in the game's opening scene, only one of the characters animates while speaking.

**Comment by Martysh12** [comment]
Oh yeah, actually, I can animate him talking too.

**Comment by Martysh12** [comment]
https://github.com/pixequil/oso-game-1/assets/49569238/a2743308-6b25-4e37-b378-4c0844477671

**Comment by pixequil** [comment]
i don't think all of the mouthless characters should use this same animation. which is why i proposed swaying in the place of this, since this is a character whose object is known for being moved in an arc

**Comment by Martysh12** [comment]
Ahh, okay

**Comment by Martysh12** [comment]
https://github.com/pixequil/oso-game-1/assets/49569238/e80995a0-5173-42b9-b72a-082d9c946700

**Comment by pixequil** [comment]
well now that it's like this, i feel like the inactive sway needs to either be way gentler or be gone, otherwise it's like btnet started talking while posty was talking

**Review by pixequil — APPROVED** [review]

**Pull request merged**
