### PR TITLE
Audio music art

### PR DESCRIPTION
**Pull request by funnyboy044**

### CODE REVIEW

**Comment by funnyboy044** [comment]
Figured I would merge this now since we're starting with imagemaps

**Comment by funnyboy044** [comment]
There's more issues i can link but there's an issue link limit on git

**Comment by funnyboy044** [comment]
> what sort of hints are neon lights and sheet meant to provide here? i checked the outline and i'm still confused.

I'm not sure about the hints myself. From what i can tell, i think some of the records to play on jukebox are hidden around the music store or map and these two guys give hints on where they are. Honestly, I don't think we need them so I can get rid of them if you think so

**Comment by funnyboy044** [comment]
It should work on the new main branch just fine

**Comment by funnyboy044** [comment]
The voices of these characters aren't final so let me know what ideas you have for character voices

**Review by pixequil — APPROVED** [review]

**Pull request merged**
