### PR TITLE
Resize all Posty sprites by a factor of 2

### LINKED ISSUE #66: Resize posty sprites
Posty's sprites look horrible when scaled, which means they need to be scaled before being shown.
~~Instead of doing that manually, a script can be written which reads a registry of sprites, and scales them accordingly.
There also need to be instructions on how to add sprites to the registry.~~

EDIT: All sprites will be scaled manually

### PR DESCRIPTION
**Pull request by Martysh12**
ImageMagick command used:
```bash
magick $file -scale 200% $file
```

Fixes #66

### CODE REVIEW

**Comment by Martysh12** [comment]
Posty is still a little anti-aliased, although it is less noticeable now.
Untitled
I think that's because she is moved to the left side of the screen.
Whatever.

**Comment by pixequil** [comment]
let's try positioning her using integer coordinates instead of aligns then, to see if that fixes the anti-aliasing problem

**Comment by Martysh12** [comment]
It's going to get annoying having to type the exact values again and again.

**Comment by Martysh12** [comment]
I suggest just leaving it at that, for now.

**Comment by pixequil** [comment]
the image processing seems to have introduced some amount of noisy crust. would you like me to run the images through a lossless photoshop batch instead? also, going through these sprites i cannot find the anti-aliasing that was mentioned

**Comment by pixequil** [comment]
ah never mind. i checked the original images and they really are there. my mistake!

**Comment by Martysh12** [comment]
...yikes. ImageMagick isn't the best tool for this. If you could, try resizing them in PhotoShop.
The anti-aliasing I mentioned earlier is a product of texture filtering in Ren'Py, meaning that pixelated images will look smoother when zoomed in.

**Comment by Martysh12** [comment]
Also, you can drag'n'drop images into text boxes in GitHub, you don't have to upload them to Discord first

**Comment by Martysh12** [comment]
I'll revert the commit, hang on

**Comment by pixequil** [comment]
image

thanks for the tip. this is how posty displays on my screen using the code and files from this branch (magnified in photoshop using nearest neighbor, to display the fine detail that's on my screen). i don't see any anti-aliasing here. were you zooming in the renpy game itself or something?

**Comment by Martysh12** [comment]
Wow okay. That's really weird, looks like it's some kind of difference between Linux and Windows. I was not doing any zooming in of any kind.

**Comment by pixequil** [comment]
thats messed up. in any case, i dont think you needed to revert the change. i was mistaken in thinking the grain was introduced during the resize- in truth, it's been on the sprites the whole time. and it's hardly a problem, clearly only noticeable when using something like photoshop's magic wand. i think your sprite resizes were an improvement. do you want to unrevert your change?

**Comment by Martysh12** [comment]
Sure, I'll do that

**Review by pixequil — APPROVED** [review]

**Pull request merged**
