### PR TITLE
queue pass 2

### LINKED ISSUE #21: retainer is sad he got eliminated
```
        p "_" # TODO: retainer is sad he got eliminated
```

undefined

### LINKED ISSUE #160: posty talks to buff and removes hamburger fire
Posty talks to Buff. 

Buff Loves history. Tells you all about history and the paintings and people in the room. Doesn't actually know anythving about history but Posty doesn't either so it's hard to call them out on it.

buff makes up some kind of fact about the painting.

posty thinks to use the heavier on the painting, removing the fire.

posty prods buff for another fact about the painting, that is now changed.

buff makes up a new fact that contradicts the previous fact.

posty calls them out on the contradiction, causing them to give posty an imaginary lighter.

posty is confused.

buff explains that imaginary things are a contradictory science, so they gave Posty a con-science lighter to make their conscience lighter after saying a contradiction outing themself as a liar. this all sounds very made-up, but, that's the nature of imaginary things.

### LINKED ISSUE #252: hint for if you got the napkin painting

### LINKED ISSUE #284: posty finally arrives with the butterfly package
```
label .cb_give:
    scene bg dome
    show posty neutral
    show cb
    p "_" # posty finally arrives with the butterfly package
    cb "_"
    show butterfly_package
    "You handed over the {b}Butterfly Package{/b}!"
    $ item.butterfly_package = False
    $ win_flag = True
    hide butterfly_package
    cb "_" # crayon box has to go start the challenge
    hide cb with moveoutright
    show posty astonished before
    cb "Gather 'round, contestants! The fourth challenge is about to start!"
    cb "I had the contents of today's challenge{nw}"
    show posty astonished anim
    cb "I had the contents of today's challenge{fast} specially delivered!"
    p "_" # posty is freaking out. crayon box is talking about ME???
    "You successfully finished your work for today!"
    p "_" # posty says something that could imply she wants to take a break in the park
    jump dome
```

### LINKED ISSUE #286: talking to automatone.
A businessman taking a break in the park, because all the construction on main street has made trying to get to work into a futile act. He mentions that things were already complicated with Blob not there to help the company, and this is another problem on top.

### PR DESCRIPTION
**Pull request by pixequil**
closes #160 
closes #284 
closes #21 
closes #286 
closes #252

### CODE REVIEW

**Comment by pixequil** [comment]
closes #173

**Comment by pixequil** [comment]
closes #284

**Comment by pixequil** [comment]
dammit, github isnt letting me attach the issue

**Review by funnyboy044 — APPROVED** [review]
good stuff

**Pull request merged**
