### PR TITLE
153 capsule gives posty the heavier

### LINKED ISSUE #152: "heavier" item description
It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It's also heavy.

### LINKED ISSUE #153: capsule gives posty the heavier
Capsule stops Posty at the entrance to the war exhibit, asking if she's strong and begging her to take this "heavier" off her hands. 

capsule is thankful. Posty asks what a heavier even is, and Capsule explains what it is. It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It's also heavy.

### PR DESCRIPTION
**Pull request by pixequil**
NOT READY FOR MERGE!!!

Needs a pass for posty's expressions. I added a new label "needs directing" for this purpose.

closes #153, closes #152

### CODE REVIEW

**Comment by Loggybears2** [comment]
oh I could add the expressions (loggybears from discord)

**Comment by Loggybears2** [comment]
unfortunately I am still learning how to actually use github, but I will try

**Comment by Loggybears2** [comment]
`label .capsulefirst:
    scene bg museum_war
    show posty neutral # !! interaction needs directing!!
    show capsule pain
    show heavier #151 
    capsule "Hey! You there, do you mind helping me out with a favor?"
    p "Huh?"
    capsule "I need your help to carry this heavy item off of my hands!"
    p happy "Oh sure! No problem!"
    show capsule happy
    show heavier 
    $ saw.war = True
    $ item.heavier = True
    "You got the {b}heavier{/b}!{p}This thing can remove a lot of fire from an area. It just requires a bit of elbow grease to get it working." 
    hide heavier # capsule is thankful. Posty asks what a heavier even is, and Capsule explains what it is. It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It's also heavy.
    p concerned "Oh wow! This sure is heavy... what even is this?"
    capsule "It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It's also heavy."
    p confused quiet "..."
    jump museum_war`

**Comment by pixequil** [comment]
you can use triple backticks for a more legible codeblock that allows line breaks

**Comment by Loggybears2** [comment]
oh okay
``` label .capsulefirst:
    scene bg museum_war
    show posty neutral # !! interaction needs directing!!
    show capsule pain
    show heavier #151 
    capsule "Hey! You there, do you mind helping me out with a favor?"
    p "Huh?"
    capsule "I need your help to carry this heavy item off of my hands!"
    p happy "Oh sure! No problem!"
    show capsule happy
    show heavier 
    $ saw.war = True
    $ item.heavier = True
    "You got the {b}heavier{/b}!{p}This thing can remove a lot of fire from an area. It just requires a bit of elbow grease to get it working." 
    hide heavier # capsule is thankful. Posty asks what a heavier even is, and Capsule explains what it is. It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It's also heavy.
    p concerned "Oh wow! This sure is heavy... what even is this?"
    capsule "It's the opposite of a lighter. Instead of adding fire to things, it removes fire from things. It's also heavy."
    p confused quiet "..."
    jump museum_war```

**Review by funnyboy044 — APPROVED** [review]
I like it

**Review by funnyboy044 — APPROVED** [review]

**Pull request merged**
