### PR TITLE
Progressive download configuration

### PR DESCRIPTION
**Pull request by pixequil**
added some files needed for web publishing

### CODE REVIEW

**Comment by pixequil** [comment]
im not totally sure what to do about this to be honest. right now i have it set up so talksprites do not download progressively. this is because the OSO game uses frame by frame animations for some of its character talksprites. if progressive downloading is enabled, those sprites will look pixelated when they play, which is weird and jarring. but with it off, i'm worried that people with slow internet connections, or, really, people with *any* internet latency, will miss the animations. is there even a solution here?

**Comment by Martysh12** [comment]
Did you test it?
Also, you can set [config.image_cache_size_mb](https://www.renpy.org/doc/html/config.html#var-config.image_cache_size_mb) to a higher value, but I'm not sure how it works.

**Comment by pixequil** [comment]
i tested it locally, but i'd need to upload it somewhere to test it with real latency, instead of simulated latency, and i haven't yet set up the infrastructure for that

**Comment by pixequil** [comment]
i think this is ready to be merged for now, at least so we can have it ready when we start web testing

**Review by funnyboy044 — APPROVED** [review]
WEB TEST TIME

**Pull request merged**
