### PR TITLE
14 toasty sprites

### PR DESCRIPTION
**Pull request by coppersalts**

### CODE REVIEW

**Comment by Martysh12** [comment]
Don't merge yet, I have a feeling Toasty's animation code can be refactored.

**Comment by pixequil** [comment]
is it broken currently? or is it in a state where attempting to use it would eventually need scripts to need heavy revision?

**Comment by pixequil** [comment]
image
this pose creates a tangent with the dialogue box. no need to fix it immediately since we don't know if the ui is final, but, i do kinda expect it to roughly occupy this much of the screen at least vertically, even if we do get rid of how much blocking it does on the right.

**Comment by Martysh12** [comment]
> is it broken currently? or is it in a state where attempting to use it would eventually need scripts to need heavy revision?

No, but I feel like the code could look a little cleaner. In any case, you can merge this pull request, because I'll just make a pull request of my own.

**Comment by pixequil** [comment]
so i went through it and, in my amateur opinion, i feel like the only long-term debt this would produce is a bunch of variable resets in scripts, if that ever got fixed. and those are pretty to search and destroy. i think we should merge this now so toasty scenes can be writable, and we can leave refactoring to a future issue, even if it starts right away.

**Pull request merged**
