### PR TITLE
Various Changes to talksprites

### PR DESCRIPTION
**Pull request by funnyboy044**
Dealing with some problems related to #218

### CODE REVIEW

**Comment by funnyboy044** [comment]
- Fixed talksprites placement and switched out better sprites for blue-colored glasses, bonbon, buff, retainer, sour gummy, and rose-colored glasses
- Also fixed issues with some characters appearing twice (just combined them) for rcg, capsule, blue tile, dolly, palettette, ahiss, and buff
- Also fixed palettette 2nd talksprite thing glitching out (callback issue)
- Also removed a sound that wasn't needed anymore

**Review by Martysh12 — CHANGES_REQUESTED** [review]
Can you remove the `fixed` from all the sprites?

**Comment by funnyboy044** [comment]
The only talksprites issues left now should be:
- Red Tile - slight white aura, can't find original user (Pigeon/APigeonWithCoffee) and picture
- Palettette - big white aura, can't find original user (Zerosiphus) and picture
- Crayon Box - big white aura, can't make transparent due to white background under sprites, sprites have weird proportions (might be fine)

**Comment by funnyboy044** [comment]
- Swapped original sprites of Crayon Box, Palettette, and Red Tile with XKZ's sprites
- Added Satomi, XKZ, and myself into programmers section
There is a 2nd set of Palettette sprites that remove the whole white halo, but they cut too deep into the sprite tbh and ruin the art
Also, keep in mind, these don't look perfect and kinda cut into the art, so we may have to change them later

**Comment by Martysh12** [comment]
Then I suggest creating an issue for later

**Review by Martysh12 — APPROVED** [review]
yup, looks good

**Review by pixequil — APPROVED** [review]

**Pull request merged**
